services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chilllink_api
    restart: always
    ports:
      - "8888:80"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    networks:
      - chilllink-net

  db:
    image: postgres:16
    container_name: chilllink_db
    restart: always
    environment:
      POSTGRES_USER: user_chl_w3Z9k4
      POSTGRES_PASSWORD: pass_9qA@1eN!b7
      POSTGRES_DB: chilllink_prod
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chilllink-net

  adminer:
    image: adminer:latest
    container_name: chilllink_adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - chilllink-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chilllink_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - chilllink-net

  mercure:
    image: dunglas/mercure
    container_name: chilllink_mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: ChangeThisMercureSecretInProd
      MERCURE_SUBSCRIBER_JWT_KEY: ChangeThisMercureSecretInProd
      MERCURE_JWT_SECRET: ChangeThisMercureSecretInProd
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous
    ports:
      - "3000:3000"
    networks:
      - chilllink-net



networks:
  chilllink-net:
    driver: bridge
