nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:5173', 'http://localhost:8888']  # frontend et Backend docker
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5174', 'http://localhost:8888'] # frontend et Backend docker
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
